// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import ResponsiveNavController from "./responsive_nav_controller"
application.register("responsive-nav", ResponsiveNavController)

import UnreadNotifsCountController from "./unread_notifs_count_controller"
application.register("unread-notifs-count", UnreadNotifsCountController)
